### Data Cleanig
* importing the data set(CSV)
* observe the Data Set
    * Identifying the rows/columns and their relation
    * Identifying the index column(primary key column)
    * check if there are any duplicate columns
    * which rows to be skipped
* Assign the index column(to avoid creation of new index column
* Skip irrelevant rows(to avoid dispaly of index row)
* Drop duplicate/iirelevant columns

In [ ]:
erpsupport@apssdc.in
allhr@apssdc.in';

In [56]:
import pandas as pd
df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)
df

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
Ivory Coast (CIV) [CIV],12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
Cyprus (CYP),9,0,1,0,1,10,0,0,0,0,19,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
Sudan (SUD),11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
Tajikistan (TJK),5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [55]:
import pandas as pd
df=pd.read_csv('olympics.csv',index_col=0,skiprows=1)
for column in df.columns:
    if column[:2]=='01':
        df.rename(columns={column:'Gold'+column[4:]},inplace=True)
    if column[:2]=='02':
        df.rename(columns={column:'Silver'+column[4:]},inplace=True)
    if column[:2]=='03':
        df.rename(columns={column:'Bronze'+column[4:]},inplace=True)
    if column[:1]=='№':
        df.rename(columns={column:'#'+column[1:]},inplace=True)
names=df.index.str.split('\s\(')
df.index=names.str[0]
#names
df['ID']=names.str[1].str[:3]    
df.drop('Totals',axis=0,inplace=True)   
df

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ
Australia,25,139,152,177,468,18,5,3,4,12,43,144,155,181,480,AUS
Austria,26,18,33,35,86,22,59,78,81,218,48,77,111,116,304,AUT
Azerbaijan,5,6,5,15,26,5,0,0,0,0,10,6,5,15,26,AZE
Bahamas,15,5,2,5,12,0,0,0,0,0,15,5,2,5,12,BAH
Bahrain,8,0,0,1,1,0,0,0,0,0,8,0,0,1,1,BRN
Barbados,11,0,0,1,1,0,0,0,0,0,11,0,0,1,1,BAR
Belarus,5,12,24,39,75,6,6,4,5,15,11,18,28,44,90,BLR
Belgium,25,37,52,53,142,20,1,1,3,5,45,38,53,56,147,BEL
Bermuda,17,0,0,1,1,7,0,0,0,0,24,0,0,1,1,BER
Bohemia,3,0,1,3,4,0,0,0,0,0,3,0,1,3,4,BOH
Botswana,9,0,1,0,1,0,0,0,0,0,9,0,1,0,1,BOT
Brazil,21,23,30,55,108,7,0,0,0,0,28,23,30,55,108,BRA
British West Indies,1,0,0,2,2,0,0,0,0,0,1,0,0,2,2,BWI
Bulgaria,19,51,85,78,214,19,1,2,3,6,38,52,87,81,220,BUL
Burundi,5,1,0,0,1,0,0,0,0,0,5,1,0,0,1,BDI
Cameroon,13,3,1,1,5,1,0,0,0,0,14,3,1,1,5,CMR
Canada,25,59,99,121,279,22,62,56,52,170,47,121,155,173,449,CAN
Chile,22,2,7,4,13,16,0,0,0,0,38,2,7,4,13,CHI
China,9,201,146,126,473,10,12,22,19,53,19,213,168,145,526,CHN
Colombia,18,2,6,11,19,1,0,0,0,0,19,2,6,11,19,COL
Costa Rica,14,1,1,2,4,6,0,0,0,0,20,1,1,2,4,CRC
Ivory Coast,12,0,1,0,1,0,0,0,0,0,12,0,1,0,1,CIV
Croatia,6,6,7,10,23,7,4,6,1,11,13,10,13,11,34,CRO
Cuba,19,72,67,70,209,0,0,0,0,0,19,72,67,70,209,CUB
Cyprus,9,0,1,0,1,10,0,0,0,0,19,0,1,0,1,CYP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Spain,22,37,59,35,131,19,1,0,1,2,41,38,59,36,133,ESP
Sri Lanka,16,0,2,0,2,0,0,0,0,0,16,0,2,0,2,SRI
Sudan,11,0,1,0,1,0,0,0,0,0,11,0,1,0,1,SUD
Suriname,11,1,0,1,2,0,0,0,0,0,11,1,0,1,2,SUR
Sweden,26,143,164,176,483,22,50,40,54,144,48,193,204,230,627,SWE
Switzerland,27,47,73,65,185,22,50,40,48,138,49,97,113,113,323,SUI
Syria,12,1,1,1,3,0,0,0,0,0,12,1,1,1,3,SYR
Chinese Taipei,13,2,7,12,21,11,0,0,0,0,24,2,7,12,21,TPE
Tajikistan,5,0,1,2,3,4,0,0,0,0,9,0,1,2,3,TJK
Tanzania,12,0,2,0,2,0,0,0,0,0,12,0,2,0,2,TAN
Thailand,15,7,6,11,24,3,0,0,0,0,18,7,6,11,24,THA
Togo,9,0,0,1,1,1,0,0,0,0,10,0,0,1,1,TOG
Tonga,8,0,1,0,1,1,0,0,0,0,9,0,1,0,1,TGA
Trinidad and Tobago,16,2,5,11,18,3,0,0,0,0,19,2,5,11,18,TRI
Tunisia,13,3,3,4,10,0,0,0,0,0,13,3,3,4,10,TUN
Turkey,21,39,25,24,88,16,0,0,0,0,37,39,25,24,88,TUR
Uganda,14,2,3,2,7,0,0,0,0,0,14,2,3,2,7,UGA
Ukraine,5,33,27,55,115,6,2,1,4,7,11,35,28,59,122,UKR
United Arab Emirates,8,1,0,0,1,0,0,0,0,0,8,1,0,0,1,UAE
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA
Uruguay,20,2,2,6,10,1,0,0,0,0,21,2,2,6,10,URU
Uzbekistan,5,5,5,10,20,6,1,0,0,1,11,6,5,10,21,UZB
Venezuela,17,2,2,8,12,4,0,0,0,0,21,2,2,8,12,VEN
Vietnam,14,0,2,0,2,0,0,0,0,0,14,0,2,0,2,VIE
Virgin Islands,11,0,1,0,1,7,0,0,0,0,18,0,1,0,1,ISV
Yugoslavia,16,26,29,28,83,14,0,3,1,4,30,26,32,29,87,YUG
Independent Olympic Participants,1,0,1,2,3,0,0,0,0,0,1,0,1,2,3,IOP
Zambia,12,0,1,1,2,0,0,0,0,0,12,0,1,1,2,ZAM
Zimbabwe,12,3,4,1,8,1,0,0,0,0,13,3,4,1,8,ZIM
Mixed team,3,8,5,4,17,0,0,0,0,0,3,8,5,4,17,ZZX

#### Data Retrieval
 * Index column
 * column names
 * second Column
 * any column
 * First row 
 * Any row
 * sinle cell data

In [3]:
df.index         #Returns the index column               
df.columns       # Returns the column names or first row
df['Total']      # returns the total column-> total medal in sub 
df['Total.1']    # returns the toal.1 column
df.iloc[[0]]
df.head(1)       # returns the sub data frame with the specific row
df.index[0]
#df.loc['India (IND) [F]'] # returns a single row
df['Gold'][4]        #returns the gold medal won by first country
df.iloc[4][1]       # return the gold medal won by fifth country
df.loc['India'][-2]

26

In [43]:
df.iloc[4][1]

3

In [4]:
df.columns

Index(['# Summer', 'Gold', 'Silver', 'Bronze', 'Total', '# Winter', 'Gold.1',
       'Silver.1', 'Bronze.1', 'Total.1', '# Games', 'Gold.2', 'Silver.2',
       'Bronze.2', 'Combined total', 'ID'],
      dtype='object')

In [83]:
df.index[-1]

'Mixed team'

0

In [84]:
df['Combined total'][-1]

17

In [87]:
df.loc['United States']['Gold.1']

96

In [88]:
abs(df.loc['United States']['Gold']-df.loc['China']['Gold'])

775

In [91]:
df['Gold.1'].max()

118

In [93]:
df['Gold'].sum()

4809

In [96]:
df['Gold']==df['Gold'].max()

Afghanistan                         False
Algeria                             False
Argentina                           False
Armenia                             False
Australasia                         False
Australia                           False
Austria                             False
Azerbaijan                          False
Bahamas                             False
Bahrain                             False
Barbados                            False
Belarus                             False
Belgium                             False
Bermuda                             False
Bohemia                             False
Botswana                            False
Brazil                              False
British West Indies                 False
Bulgaria                            False
Burundi                             False
Cameroon                            False
Canada                              False
Chile                               False
China                               False
Colombia                            False
Costa Rica                          False
Ivory Coast                         False
Croatia                             False
Cuba                                False
Cyprus                              False
                                    ...
Spain                               False
Sri Lanka                           False
Sudan                               False
Suriname                            False
Sweden                              False
Switzerland                         False
Syria                               False
Chinese Taipei                      False
Tajikistan                          False
Tanzania                            False
Thailand                            False
Togo                                False
Tonga                               False
Trinidad and Tobago                 False
Tunisia                             False
Turkey                              False
Uganda                              False
Ukraine                             False
United Arab Emirates                False
United States                        True
Uruguay                             False
Uzbekistan                          False
Venezuela                           False
Vietnam                             False
Virgin Islands                      False
Yugoslavia                          False
Independent Olympic Participants    False
Zambia                              False
Zimbabwe                            False
Mixed team                          False
Name: Gold, Length: 146, dtype: bool

In [52]:
df[df['Gold']==df['Gold'].max()].index[0]

'United States'

In [53]:
df[df['Combined total'].max() == df['Combined total']]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA

In [54]:
df_gold = df[(df['Gold']>0) & (df['Gold.1']>0)]
df_gold

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Australia,25,139,152,177,468,18,5,3,4,12,43,144,155,181,480,AUS
Austria,26,18,33,35,86,22,59,78,81,218,48,77,111,116,304,AUT
Belarus,5,12,24,39,75,6,6,4,5,15,11,18,28,44,90,BLR
Belgium,25,37,52,53,142,20,1,1,3,5,45,38,53,56,147,BEL
Bulgaria,19,51,85,78,214,19,1,2,3,6,38,52,87,81,220,BUL
Canada,25,59,99,121,279,22,62,56,52,170,47,121,155,173,449,CAN
China,9,201,146,126,473,10,12,22,19,53,19,213,168,145,526,CHN
Croatia,6,6,7,10,23,7,4,6,1,11,13,10,13,11,34,CRO
Czech Republic,5,14,15,15,44,6,7,9,8,24,11,21,24,23,68,CZE
Czechoslovakia,16,49,49,45,143,16,2,8,15,25,32,51,57,60,168,TCH
Estonia,11,9,9,15,33,9,4,2,1,7,20,13,11,16,40,EST
Finland,24,101,84,117,302,22,42,62,57,161,46,143,146,174,463,FIN
France,27,202,223,246,671,22,31,31,47,109,49,233,254,293,780,FRA
Germany,15,174,182,217,573,11,78,78,53,209,26,252,260,270,782,GER
United Team of Germany,3,28,54,36,118,3,8,6,5,19,6,36,60,41,137,EUA
East Germany,5,153,129,127,409,6,39,36,35,110,11,192,165,162,519,GDR
West Germany,5,56,67,81,204,6,11,15,13,39,11,67,82,94,243,FRG
Great Britain,27,236,272,272,780,22,10,4,12,26,49,246,276,284,806,GBR
Italy,26,198,166,185,549,22,37,34,43,114,48,235,200,228,663,ITA
Japan,21,130,126,142,398,20,10,17,18,45,41,140,143,160,443,JPN
Kazakhstan,5,16,17,19,52,6,1,3,3,7,11,17,20,22,59,KAZ
South Korea,16,81,82,80,243,17,26,17,10,53,33,107,99,90,296,KOR
Netherlands,25,77,85,104,266,20,37,38,35,110,45,114,123,139,376,NED
Norway,24,56,49,43,148,22,118,111,100,329,46,174,160,143,477,NOR
Poland,20,64,82,125,271,22,6,7,7,20,42,70,89,132,291,POL
Russia,5,132,121,142,395,6,49,40,35,124,11,181,161,177,519,RUS
Soviet Union,9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204,URS
Unified Team,1,45,38,29,112,1,9,6,8,23,2,54,44,37,135,EUN
Slovakia,5,7,9,8,24,6,2,2,1,5,11,9,11,9,29,SVK
Slovenia,6,4,6,9,19,7,2,4,9,15,13,6,10,18,34,SLO
Spain,22,37,59,35,131,19,1,0,1,2,41,38,59,36,133,ESP
Sweden,26,143,164,176,483,22,50,40,54,144,48,193,204,230,627,SWE
Switzerland,27,47,73,65,185,22,50,40,48,138,49,97,113,113,323,SUI
Ukraine,5,33,27,55,115,6,2,1,4,7,11,35,28,59,122,UKR
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA
Uzbekistan,5,5,5,10,20,6,1,0,0,1,11,6,5,10,21,UZB